import './big-picture.js';
import { addPictures } from './min-picture.js';
import './min-picture.js';
import './data.js';
import './utils.js';
import './form.js';
import {uploadFormOpen, uploadFormClose} from './form.js';
uploadFormOpen();
uploadFormClose();
addPictures();
